---
project_name: epinio-ui

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
    format: binary
    format_overrides:
      - goos: windows
        format: zip

before:
  hooks:
    - sh -c "cd src/jetstream && go mod download"
    - sh -c "cd src/jetstream && go get github.com/swaggo/swag/cmd/swag@v1.6.7 && swag init"

builds:
  - id: epinio-ui
    dir: src/jetstream
    binary: epinio-ui
    ldflags:
      - -w -s
      - -X "main.appVersion={{ .Tag }}"
    goos:
      - linux
      # - darwin
      # - windows
    goarch:
      - amd64
      # - arm64
      # - arm

changelog:
  skip: false

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  -
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: epinio-ui

    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # IDs to filter the binaries/packages.
    ids:
    - epinio-ui

    # Templates of the Docker image names.
    image_templates:
    - "ghcr.io/epinio/epinio-ui:{{ .Tag }}"
    - "ghcr.io/epinio/epinio-ui:latest"

    # Skips the docker push.
    #skip_push: "true"

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

    use: docker

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=epinio.io.ui.source={{.Env.UI_BUNDLE_URL}}"
    - "--label=org.opencontainers.image.source=https://github.com/epinio/ui-backend"
    - "--build-arg=DIST_BINARY=epinio-ui"
    - "--platform=linux/amd64"

    # If your Dockerfile copies files other than binaries and packages,
    # you should list them here as well.
    # Note that GoReleaser will create the same structure inside a temporary
    # folder, so if you add `foo/bar.json` here, on your Dockerfile you can
    # `COPY foo/bar.json /whatever.json`.
    # Also note that the paths here are relative to the folder in which
    # GoReleaser is being run (usually the repository root folder).
    # This field does not support wildcards, you can add an entire folder here
    # and use wildcards when you `COPY`/`ADD` in your Dockerfile.
    extra_files:
    - ui/
