name: Delete old container images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # every day at 6 in the morning

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged and dev containers older than a week
        uses: snok/container-retention-policy@v1.5.1
        with:
          image-names: epinio-ui
          cut-off: A week ago UTC
          account-type: org
          org-name: epinio
          keep-at-least: 1
          filter-tags: v*-g*
          filter-include-untagged: true
          token: ${{ secrets.IMG_CLEANUP_TOKEN }}
