name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
  # nightly
  schedule:
    - cron:  '0 0 * * *'

env:
  SETUP_GO_VERSION: '1.17'

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Setup Deps
        run: cd src/jetstream && go get github.com/swaggo/swag/cmd/swag@v1.6.7 && swag init

      - name: Lint
        run: cd src/jetstream && go vet ./...

      - name: Unit Tests
        run: cd src/jetstream && go test -v ./...
