name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  # nightly
  schedule:
    - cron:  '0 0 * * *'

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Lint
        run: cd src/jetstream && go vet ./...

      - name: Unit Tests
        run: cd src/jetstream && go test -v ./...
