name: Release Test

on:
  workflow_dispatch:

env:
  # change this to embed a different UI dashboard
  UI_BUNDLE_URL: https://github.com/rancher/dashboard/releases/download/epinio-standalone-v0.9.0-0.0.1/rancher-dashboard-epinio-standalone-embed.tar.gz

jobs:
  release:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      # A tag is mandatory but it will not be pushed in the repo
      # because we do not release
      -
        name: Create fake tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v99.0.0 -m "Fake tag for QA" --force
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to avoid quota
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JUADK_DOCKERHUB_USERNAME }}
          password: ${{ secrets.JUADK_DOCKERHUB_PASSWORD }}
      -
        name: Download dashboard
        run: |
          mkdir ui
          wget "${{ env.UI_BUNDLE_URL }}"
          tar xfz *.tar.gz -C ui
      -
        name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 1.8.2
          args: release --skip-announce --skip-validate --skip-sign --config .goreleaser-test.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
