name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

env:
  SETUP_GO_VERSION: '1.18'
  # change this to embed a different UI dashboard
  UI_BUNDLE_URL: https://github.com/rancher/dashboard/releases/download/epinio-standalone-v1.7.0-0.0.1/rancher-dashboard-epinio-standalone-embed.tar.gz

jobs:
  release:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Download dashboard
        run: |
          mkdir ui
          wget "${{ env.UI_BUNDLE_URL }}"
          tar xfz *.tar.gz -C ui
      -
        name: Get current tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      -
        name: Run GoReleaser Cross
        run: ./build/bk-release.sh release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UI_BUNDLE_URL: "${{ env.UI_BUNDLE_URL }}"

      # Allow to release Epinio UI Helm chart automatically when we release Epinio.
      # The tag is sent to the Helm chart repo.
      -
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CHART_REPO_ACCESS_TOKEN }}
          repository: epinio/helm-charts
          event-type: epinio-ui-release
          client-payload: '{"ref": "${{ steps.get_tag.outputs.TAG }}"}'
